# Generated by Django 6.0 on 2025-12-04 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('sport', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball')], default='football', max_length=20)),
                ('home_odds', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('draw_odds', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('away_odds', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('choice', models.CharField(max_length=50)),
                ('won', models.BooleanField(null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.match')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
